name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      SPACE_APP_KEYSTORE_PATH: "./space_release.jks"
      SPACE_APP_KEYSTORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}
      SPACE_APP_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}
      SPACE_APP_API_KEY: ${{ secrets.API_KEY }}
      SPACE_APP_FABRIC_KEY: ${{ secrets.FABRIC_KEY }}
      SPACE_APP_GOOGLE_MAPS_KEY: ${{ secrets.GOOGLE_MAPS_KEY }}

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create keystore
      run: echo ${{ secrets.RELEASE_KEYSTORE_BASE64 }} | base64 -d > space_release.jks
    - name: Build with Gradle
      run: ./gradlew buildDebug
    - name: Assemble apk with Gradle
      run: ./gradlew assembleDebug
    - name: Publish artefact
      uses: actions/upload-artifact@v1
      with:
        name: app-debug
        path: app/build/outputs/apk